person:
  userName: "zhangsan \n 李四"
#单引号会将＼n作为字符串输出;双引号会将＼n 作为换行输出<控制台打印>
#双引号不会转义，单引号会转义(再加斜杠)<网页上>

  boss: true
  birth: 2019/12/9
  age: 19
#  interests: [足球，篮球]
  interests:
    - 篮球
    - 足球
    - 18
  animal: [阿猫，阿狗]
#  score:
#    english: 80
#    math: 90
  score: {english: 80,math: 90}
  salarys:
    - 9999.98
    - 9999.99
  pet:
    name: 阿狗
    weight: 9999
  allPets:
    sick:
      - {name: 阿狗,weight: 9999}
      - name: 阿猫
        weight: 8888
      - name: 阿虫
        weight: 1111
    health:
      - {name: 阿星,weight: 1199}
      - name: 阿龙
        weight: 8880
